### ISSUE TITLE
перенос функции draw_board

### ISSUE THREAD

**Issue by ihsinme** [Arti0mka/Projekt1pository#13]
необходимо что бы в tele.py можно было использовать функции из ADD file.py. для этого нужно их скопировать в файл tele и попробывать запустить. берем первую функцию и по команде tt выполняем ее.

вот оригинальная функция. 
```py
board = list(range(1,10))

def draw_board(board):
    print ("-" * 13)
    for i in range(3):
        print ("|", board[0+i*3], "|", board[1+i*3], "|", board[2+i*3], "|")
        print ("-" * 13)

```
проблема в том что оператор print будет выводить в консоль а не в телеграм канал. поэтому тебе необходимо поменять принт на 
```py
bot.send_message
```
но это потребует еще увеличить параметры в функции 
```py
def draw_board(board):
```

**Comment by Arti0mka** [comment]
Дядя Сергей я использую команду не tt, а TT

**Comment by Arti0mka** [comment]
Дядя Сергей поможите увеличить параметры в функции
```py
def draw_board(board):
```

**Comment by ihsinme** [comment]
```py
board = list(range(1,10))

def draw_board(board,bot,message):
    bot.send_message(message.from_user.id, "-" * 13)
    for i in range(3):
        bot.send_message(message.from_user.id,"|"+ str(board[0+i*3])+ "|"+ str(board[1+i*3])+ "|"+ str(board[2+i*3])+ "|")
        bot.send_message(message.from_user.id, "-" * 13)    
```
я бы поробывал что то такое, потом посмотрел ошибки и подправил.
особо обрати внимание
```py
         print ("|", board[0+i*3], "|", board[1+i*3], "|", board[2+i*3], "|")
        bot.send_message(message.from_user.id,"|"+ str(board[0+i*3])+ "|"+ str(board[1+i*3])+ "|"+ str(board[2+i*3])+ "|")
```
на эту замену тут и формат строки тоже изменен 
посмотри подумай почему так.


### на будущее присылай как ты делал и задавай вопрос более точечно-конкретно.

**Comment by ihsinme** [comment]
# время идет нужно двигаться дальше

жду от тебя вопросов или решений

**Comment by Arti0mka** [comment]
Дядя Сергей подскажите пожалуйста как убрать ошибку тут
```py
for i in range(3): 
```

**Comment by ihsinme** [comment]
скопируй больше информации  
1. текст ошибки  
2. код который ты вставил.

**Comment by Arti0mka** [comment]
```py
board = list(range(1,10))

def draw_board(board,bot,message):
        bot.send_message(message.from_user.id, "-" * 13)
    for i in range(3):                                                                         
        bot.send_message(message.from_user.id,"|"+ str(board[0+i*3])+ "|"+ str(board[1+i*3])+ "|"+ str(board[2+i*3])+ "|")
        bot.send_message(message.from_user.id, "-" * 13)    
    else:     
```

**Comment by Arti0mka** [comment]
```py
File "/workspace/Projekt1pository/tele.py", line 30
    for i in range(3):                                                                         
                                                                                              ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by ihsinme** [comment]
```py
def draw_board(board,bot,message):
    bot.send_message(message.from_user.id, "-" * 13)
    for i in range(3):                                                                         
        bot.send_message(message.from_user.id,"|"+ str(board[0+i*3])+ "|"+ str(board[1+i*3])+ "|"+ str(board[2+i*3])+ "|")
        bot.send_message(message.from_user.id, "-" * 13)        
```
посмотри в чем разница у тебя и уменя. смещения в твоем случае у первой строки функции 8 пробелов у второй 4 и компилятор давольно логично (на английском говорит что 2 срока не соответствует уровню отступа). фактически отступ это как begin end  в паскале и если ты сделал 8 то должен делать 8 или больше.

я исправил так я сделал 4 для функции и еще 4 для for. ниже я напишу как этот код выглядел бы в паскале. сразу скажу что он не рабочий и только для понимания.
```py
def draw_board(board,bot,message):
begin
    bot.send_message(message.from_user.id, "-" * 13)
    for i in range(3):
    begin                                                                         
        bot.send_message(message.from_user.id,"|"+ str(board[0+i*3])+ "|"+ str(board[1+i*3])+ "|"+ str(board[2+i*3])+ "|")
        bot.send_message(message.from_user.id, "-" * 13)
    end
end        
```

**Comment by ihsinme** [comment]
в коде у тебя есть еще ошибка с else, я думаю ты ее ошибочно прихватил при обработке в телеграм боте.

**Comment by Arti0mka** [comment]
да я случайно

**Comment by ihsinme** [comment]
> в коде у тебя есть еще ошибка с else, я думаю ты ее ошибочно прихватил при обработке в телеграм боте.

да я случайно.
надо писать так.
1. три точки на моем сообщении
2. quote replay

**Comment by Arti0mka** [comment]
Дядя Сергей я сделал, но у меня когда ввожу боту, то выдаёт ошибку.
```py
elif message.text == "TT":
        def draw_board(board,bot,message):
         bot.send_message(message.from_user.id, "-" * 13)
    for i in range(3):                                                                         
         bot.send_message(message.from_user.id,"|"+ str(board[0+i*3])+ "|"+ str(board[1+i*3])+ "|"+ str(board[2+i*3])+ "|")
         bot.send_message(message.from_user.id, "-" * 13)   
```

**Comment by ihsinme** [comment]
ты меня вообще не слушаешь.
1. выше я говорил про отступы у тебя опять for левее def.
2. но ошибка еще и в том что функцию надо описывать выше и вызывать потом.
не спеши подумай.

попробуй написать вопросы на которые я отвечу да или нет и которые (вопросы) тебе помогут двинуться вперед. колличество вопросов пока не ограничено, но не забудь пронумеровать.

**Comment by Arti0mka** [comment]
```py 
elif message.text == "TT":
        def draw_board(board,bot,message):
         bot.send_message(message.from_user.id, "-" * 13)
        for i in range(3):                                                                         
         bot.send_message(message.from_user.id,"|"+ str(board[0+i*3])+ "|"+ str(board[1+i*3])+ "|"+ str(board[2+i*3])+ "|")
         bot.send_message(message.from_user.id, "-" * 13)  
```
Так

**Comment by ihsinme** [comment]
ты меня вообще не слушаешь.
1. выше я говорил про отступы у тебя опять for левее def.
2. но ошибка еще и в том что функцию надо описывать выше и вызывать потом.
не спеши подумай.

попробуй написать вопросы на которые я отвечу да или нет и которые (вопросы) тебе помогут двинуться вперед. колличество вопросов пока не ограничено, но не забудь пронумеровать.

**Comment by Arti0mka** [comment]
1)Надо что нибудь изменять в строках?
2)Правильная функция? 
 ```py 
bot.send_message(message.from_user.id,"|"+ str(board[0+i*3])+ "|"+ str(board[1+i*3])+ "|"+ str(board[2+i*3])+ "|")
         bot.send_message(message.from_user.id, "-" * 13)
  ```

**Comment by ihsinme** [comment]
> 1)Надо что нибудь изменять в строках?
> 2)Правильная функция?
> 
> ```python
> bot.send_message(message.from_user.id,"|"+ str(board[0+i*3])+ "|"+ str(board[1+i*3])+ "|"+ str(board[2+i*3])+ "|")
>         bot.send_message(message.from_user.id, "-" * 13)
> ```

ну во первых функция должна начинаться у края листа со слова деф и имени функции
во вторых ты должен понимать что ты хочешь написать)
