### ISSUE TITLE
ВАЖНАЯ ЗАДАЧА. 

### ISSUE THREAD

**Issue by ihsinme** [Arti0mka/Projekt1pository#17]
нужно поработать над тем что бы создать файл (допустим tele2.py) который будет работать следующим образом.
1. он приймет от тебя сообщение для допустим твоего папы и передас это сообщение папе и только папе.
2. он приймет сообщение от вероники и передаст только маме
3. и назад

это надо научиться делать что бы ты мог играть с кем то через телеграм

удачи

**Comment by Arti0mka** [comment]
Дядя Сергей эта функция для того чтобы определять действительно или недействительно?
```py
valid = False
    while not valid:
        valid = True
```

**Comment by ihsinme** [comment]
> Дядя Сергей эта функция для того чтобы определять действительно или недействительно?
> 
> ```python
> valid = False
>     while not valid:
>         valid = True
> ```

эта функция что бы ставить крестик нолик. переменная valid  в изначальной функции использовалась что бы продолжать ввод пока ты не введешь коректные данные (от 1 до 9  и н езанятые) тут я убрал эту функциональность сделав valid сразу True

**Comment by Arti0mka** [comment]
А эта функция правильная или ошибочная?

**Comment by Arti0mka** [comment]
Просто сразу кинулась в глаза и долго не мог понять для чего.

**Comment by ihsinme** [comment]
> Просто сразу кинулась в глаза и долго не мог понять для чего.

согласен что эта функци выглядит странно. но обрати внимание что в консоли ты мог оставлять while так как косоль работает напрямую с тобой. а вот в телеграме логика работы другая ты пишешь в телефоне от туда сообщения летят на сервер телеграма а от сервера летят на твою питоновскую программу. и фактически если мы попробуем оставить тут while как в консоли то мы не получим следующее сообщение от сервера телеграма.

ошибку надо искать двумя путями
1. описать что каждая функция делает и сравнить как она работала в консоли.
2. попробывать поработать с программой (например поиграть несколько раз)

**Comment by Arti0mka** [comment]
Спасибо

**Comment by Arti0mka** [comment]
Я так понял что while важная  функция и если её убрать то ничего не работает.

**Comment by Arti0mka** [comment]
Дядя Сергей а  для чего эта функция?
```py
draw_board(bot,message,board)
    elif "aa" in message.text:
```

**Comment by ihsinme** [comment]
draw_board нарисовать доску если с английского.
эта функция рисуют доску для игры

**Comment by Arti0mka** [comment]
А спасибо

**Comment by Arti0mka** [comment]
А ошибка может быть в пробелах?

**Comment by Arti0mka** [comment]
А для чего эта функция?
```py
@bot.message_handler(content_types=['text'])
def get_text_messages(message):
    global stateGame
    global countGame
    print(stateGame)
    print(countGame)
```

**Comment by ihsinme** [comment]
> А ошибка может быть в пробелах?

если бы ошибка была в пробелах у тебя бы не работала программа. попробуй в любой строчке добавить пробел и попробуй запустить

**Comment by ihsinme** [comment]
get_text_messages эта функция принимает сообщения от сервера телеграм. фактически она вызывается каждый раз когда когда ты пишешь что то в свой бот. и то что ты пишешь поподает в переменную message

**Comment by Arti0mka** [comment]
А можете сказать для чего эта функция?
```py
 elif stateGame >= 1 and message.text.isdigit():
        stateGame = 2
```

**Comment by ihsinme** [comment]
это не функция а блок elif в который попадает при условии что состояние игры не 0 и сообщение цифра.

ну и если это так то состояние игры переходит в 2

**Comment by Arti0mka** [comment]
А эта функция?
```py
#bot.send_message(message.from_user.id,"Куда поставим " + player_token+"? ")
```

**Comment by ihsinme** [comment]
> А эта функция?
> 
> ```python
> #bot.send_message(message.from_user.id,"Куда поставим " + player_token+"? ")
> ```

обрати внимание на # в начале строки -- это значит что это коментарий, а значит они не выполняется во время работы

**Comment by Arti0mka** [comment]
Дядя Сергей это не ошибка?
```py
elif "aa" in message.text:
        take_input(bot,message,"X")
```

**Comment by ihsinme** [comment]
В чем тут ты видишь ошибку

**Comment by Arti0mka** [comment]
Дядя Сергей здравствуйте можите пожалуйста подсказать с решением задач? Можите написать или можем выйти на связь если вам не тяжело?

**Comment by ihsinme** [comment]
давай на связь вечером. 
а по поиску ошибки 

> 2\. попробывать поработать с программой (например поиграть несколько раз)

я уже подсказывал, но вероятно ты не все мои подсказки использовал

**Comment by Arti0mka** [comment]
Дядя Сергей простите я не заметил.

**Comment by Arti0mka** [comment]
Дядя Сергей помогите пожалуйста у меня не заходится в воркспейс.

**Comment by ihsinme** [comment]
sorry for the delay in reply.

look, you can open a new workspace.
while you have already done it.
to do this, you need to write in the browser.
  https://gitpod.io/#https://github.com/Arti0mka/Projekt1pository

hope this helps.

**Comment by Arti0mka** [comment]
There is an error in this function.
```py
elif stateGame == 0 and message.text == "gogo":
        stateGame = 1
        countGame = 0
        draw_board(bot,message,board)
    elif stateGame >= 1 and message.text.isdigit():
        stateGame = 2
```
Only I can't figure out where?

**Comment by ihsinme** [comment]
I would like to clarify.

1. were you able to start and play?
2. what error the compiler writes.
3. it would be good form, after a month of searching for an error, to be more verbose and describe it.

**Comment by Arti0mka** [comment]
The mistake is that if I play and then write "gogo" again, the game will continue and I will play until I run out of free cells.

**Comment by Arti0mka** [comment]
Sorry if you delayed solving the problem.

**Comment by ihsinme** [comment]
yes i agree this is the right place.
now it remains to decide what to do to make the board clean after gogo.

Any suggestions?

**Comment by Arti0mka** [comment]
It is necessary to write a command after "gogo". For example when I write "gogo" so that the board is always cleared.

**Comment by ihsinme** [comment]
well done.
I totally agree.
try to insert
```py
board = list (range (1,10))
```
front
```py
        stateGame = 1
        countGame = 0
        draw_board(bot,message,board)
```
just do not forget about the importance of spaces, there should be the same number of them in all lines of the same block.
