### ISSUE TITLE
поменяй алгоритм выигрыша

### ISSUE THREAD

**Issue by ihsinme** [Arti0mka/Projekt1pository#7]
необходимо поменять алгоритм выигрыша что бы выигрывал не тот кто ставит три крестика или нолика в один ряд. 
а допустим тот кто савит углом 
  x
x  x

рассуждение и сложности описывай внутри этой задачи, код который изменяешь тоже вставляй в эту задачу.

**Comment by ihsinme** [comment]
вот функция определения выигрыша. она называется check_win переводиться как?

```php
def check_win(board):
    win_coord = ((0,1,2),(3,4,5),(6,7,8),(0,3,6),(1,4,7),(2,5,8),(0,4,8),(2,4,6))
    for each in win_coord:
        if board[each[0]] == board[each[1]] == board[each[2]]:
            return board[each[0]]
    return False
```

**Comment by Arti0mka** [comment]
Я выполнил.
 def check_win(board):
    win_coord = ((2,1,4),(2,3,6),(6,9,8),(4,7,8),(2,5,4),(2,5,6),(6,5,8),(4,5,8),(1,4,5),(3,6,5),(4,7,8),(5,8,9),(5,6,9),(5,4,7))
    for each in win_coord:
        if board[each[0]] == board[each[1]] == board[each[2]]:
            return board[each[0]]
    return False 
Вот кусочек кода

**Comment by Arti0mka** [comment]
Я выполнил.
def check_win(board):
win_coord = ((2,1,4),(2,3,6),(6,9,8),(4,7,8),(2,5,4),(2,5,6),(6,5,8),(4,5,8),(1,4,5),(3,6,5),(4,7,8),(5,8,9),(5,6,9),(5,4,7))
for each in win_coord:
if board[each[0]] == board[each[1]] == board[each[2]]:
return board[each[0]]
return False
Вот кусочек кода

**Comment by ihsinme** [comment]
хорошо.
так красивей. (поэтому код обрамляй так в перед кодом \`\`\`py после кода \`\`\`)
Я выполнил.
```py
def check_win(board):
win_coord = ((2,1,4),(2,3,6),(6,9,8),(4,7,8),(2,5,4),(2,5,6),(6,5,8),(4,5,8),(1,4,5),(3,6,5),(4,7,8),(5,8,9),(5,6,9),(5,4,7))
for each in win_coord:
 if board[each[0]] == board[each[1]] == board[each[2]]:
  return board[each[0]]
return False
```
Вот кусочек кода

**Comment by Arti0mka** [comment]
"
def check_win(board):
    win_coord = ((0,2),(0,6),(2,8),(0,3,6),(6,8),(1,7),(3,5),(0,8),(2,6))
    for each in win_coord:
        if board[each[0]] == board[each[1]] == board[each[2]]:
            return board[each[0]]
    return False
"

**Comment by Arti0mka** [comment]
"def check_win(board):
    win_coord = ((0,2),(0,6),(2,8),(0,3,6),(6,8),(1,7),(3,5),(0,8),(2,6))
    for each in win_coord:
        if board[each[0]] == board[each[1]] == board[each[2]]:
            return board[each[0]]
    return False"

**Comment by Arti0mka** [comment]
```pydef check_win(board):
    win_coord = ((0,2),(0,6),(2,8),(0,3,6),(6,8),(1,7),(3,5),(0,8),(2,6))
    for each in win_coord:
        if board[each[0]] == board[each[1]] == board[each[2]]:
            return board[each[0]]
    return False```
