### ISSUE TITLE
Открой задачу мне кажется ты не решил не правильно

### ISSUE THREAD

**Issue by ihsinme** [Arti0mka/Projekt1pository#9]
https://github.com/Arti0mka/Projekt1pository/issues/8

**Comment by Arti0mka** [comment]
Дядя Сергей подскажите пожалуйста, а то я не понимаю.

**Comment by ihsinme** [comment]
смотри 
1. нажми на восьмерку которая выше. попадешь на задачу которую ты закрыл. попробуй ее открыть заново. должна быть кнопка reopen.  
2. когда откроешь ту задачу в ней и продолжим общение. но первое что ты сделай это повтори что делал раньше и проверь работает ли програма после твоих исправлений

**Comment by Arti0mka** [comment]
def check_win(board):
    win_coord = ((0,2),(0,6),(2,8),(0,3,6),(6,8),(1,7),(3,5),(0,8),(2,6))
    for each in win_coord:
        if board[each[0]] == board[each[1]] == board[each[2]]:
            return board[each[0]]
    return False
А теперь?

**Comment by ihsinme** [comment]
давай смотреть 
1. задачу 8 ты так и не открыл. постарайся.
2. по твоему коду наверно так красивей смотреть
```py
def check_win(board):
    win_coord = ((0,2),(0,6),(2,8),(0,3,6),(6,8),(1,7),(3,5),(0,8),(2,6))
    for each in win_coord:
        if board[each[0]] == board[each[1]] == board[each[2]]:
            return board[each[0]]
    return False
```
как его делать таким красивым я писал. посмотри в предыдущих задачах вкладка close
3. теперь по самому коду, при запуске мне кажеться должна быть ошибка. например (0,2) говорит о том что each[2] выдаст ошибку т.к. элементов только два.

4. теперь главное не суется попробывать запустить свой код и проверить его в разных ситуациях.
5. попробывать расписать что делает оригинальная функция на каждом шаге.

**Comment by Arti0mka** [comment]
```py def check_win(board):
    win_coord = ((0,2),(0,6),(2,8),(0,3,6),(6,8),(1,7),(3,5),(0,8),(2,6))
    for each in win_coord:
        if board[each[0]] == board[each[1]] == board[each[2]]:
            return board[each[0]]
    return False
